"""Explicit current-frame observations, not automatically inferred approvals.

Entries are added only after viewing the corresponding full-frame/crop evidence.
Visual shape is not a claim about simulation asset identity or pixel visibility.
"""

# One entry per prediction for FP, one per resolved truth for LOSS.
OBS = {
    'E01': [('cabinet_like', '青色柜状块体的灰色正面面板、顶面、侧面及深色底座；预测框覆盖该块体。')],
    'E02': [
        ('mixed_structure', '后方灰色立面、前景深色粗杆及右下青色块体角共同进入预测框，不能归为单一杆体。'),
        ('mixed_structure', '同一重叠结构：灰色立面、粗杆和青色块体角；不是新增独立样本。'),
        ('mixed_structure', '同图同一灰色立面与杆体、青色块体重叠区，框内为混合结构。'),
        ('mixed_structure', '同图同一混合结构重复出现：粗杆遮住后方灰色立面，右下为青色块体。'),
    ],
    'E03': [
        ('facade_like', '右图缘截断的灰色立面样块体、深色内嵌面板及底座，框含少量地面。'),
        ('facade_like', '同一右缘灰色立面与深色面板局部，出画截断；与另一类别框重叠。'),
        ('facade_like', '右缘同一立面样局部被预测为电抗器，没有可辨圆柱主体；不能据外形推断资产。'),
    ],
    'E04': [('facade_like', '灰色矩形立面样块体，正面大面积深色内嵌矩形及底座；不是可辨电容器结构。')],
    'E05': [('facade_like', '冷暗光下灰色矩形立面样块体，宽正面、深色内嵌面板和底座可辨。')],
    'E06': [
        ('cabinet_like', '青色柜状块体正面灰面板、左侧、顶面及深色基座，整体可辨。'),
        ('cabinet_like', '同一青色柜状块体正面面板及侧面、顶面、基座；两组同seed重复预测同一结构。'),
    ],
    'E07': [('cabinet_like', '青色柜状块体宽侧背面、顶面及基座；框内不包含左侧粗杆主体，无正面面板。')],
    'E08': [('mixed_structure', '冷暗光下前景粗杆遮住后方灰色立面，右下叠有青色柜状块体；是混合结构。')],
    'E09': [('unknown_instance_content', '远侧多柜沿视线叠置，仅横向顶面及侧面条带；下部被近柜遮挡，不能可靠分清框内各实例像素边界。')],
    'E10': [('recognizable_truncated', '灰色变压器宽主体、顶面三个端子及深色基座可辨；右侧出画，非仅基座。')],
    'E11': [('unknown_instance_content', '背景变体中远侧多柜叠置，青色顶面及窄横向侧面条带可见；实例边界无法仅由RGB可靠确认。')],
    'E12': [('unknown_instance_content', '背景变体中目标框含柜顶及窄侧面，并覆盖大片前景柜顶；遮挡下各实例像素归属不确定。')],
    'E13': [('recognizable_occluded', '光照变体的柜体正面面板、顶面及侧面清楚，左下被前景柜顶遮挡，仍有宽主体内容。')],
    'E14': [('recognizable_truncated', '材质变体右图缘变压器宽主体、窄顶面、三个端子和基座可见，右侧截断。')],
    'E15': [('recognizable_truncated', '光照变体右缘深色变压器宽主体、顶面端子和基座可辨，右侧截断。')],
    'E16': [('recognizable_occluded_truncated', '灰色变压器宽主体和顶面端子可见，前景粗杆遮挡中间，左缘截断。')],
    'E17': [('recognizable_truncated', '近景变压器宽顶面、三个端子及上部侧面清楚，下部出画；不是微小目标。')],
    'E18': [('recognizable', '电抗器圆柱主体、椭圆顶面及基座完整可辨，未见明显前景遮挡。')],
    'E19': [('recognizable', '孤立柜体宽侧背面、顶面和基座可辨，正面面板背向相机。')],
    'E20': [('recognizable', '电容器组宽侧背面与底座清楚，表面有斜向明暗变化，未见显著前景遮挡。')],
    'E21': [('recognizable_truncated', '右下近景柜体宽顶面和侧面可见，右侧及下部出画；后方有相邻柜，不把它们合并为本实例。')],
    'E22': [('recognizable_truncated', '灰色变压器宽主体、顶面三个端子及基座可辨，右侧出画。')],
    'E23': [('recognizable', '灰色电抗器圆柱主体及基座清楚，顶面呈窄边，未见前景遮挡。')],
    'E24': [('unknown_instance_content', '光照变体中远柜叠置，仅顶面和横向窄侧面露出，近柜遮挡下部；实例像素边界不确定。')],
    'E25': [('recognizable', '近景灰色变压器宽顶面、三个端子、两侧主体及基座完整清楚。')],
    'E26': [('recognizable_occluded', '灰色柜体顶面及宽侧背面可辨，下方部分被前景变压器顶面遮挡。')],
    'E27': [('recognizable_occluded', '后方灰色变压器宽主体、顶面三个端子可辨，右下部分被前景柜顶遮挡。')],
    'E28': [('unknown_instance_content', '右缘多个相邻柜体前后叠置且截断，仅见顶面与窄侧面，目标像素边界不确定。')],
    'E29': [('recognizable_occluded', '远侧变压器主体与三个端子可辨，前景杆遮住右侧一条区域；不是全遮挡。')],
    'E30': [('unknown_instance_content', '左图缘仅有叠置柜体局部横向顶面及侧面，目标出画且被前景柜遮挡，像素归属不确定。')],
    'E31': [('recognizable_occluded', '灰色电抗器圆顶及上部圆柱可辨，下部被前景变压器挡住；框内浅色端子属于前景，不归给电抗器。')],
    'E32': [('recognizable', '背景变体电抗器宽圆柱主体和基座可辨，未见前景遮挡。')],
    'E33': [('recognizable_truncated', '左图缘柜体宽侧背面、顶面和基座可辨，左侧与下部截断，没有正面面板。')],
    'E34': [('limited_occluded', '远侧电抗器仅上部深灰圆柱局部露在前景柜上方；下部主体及基座遮挡，内容有限但不是仅基座。')],
    'E35': [('recognizable_truncated', '前景柜体大面积顶面、上部正面及部分面板清楚，底部出画。')],
    'E36': [('recognizable_truncated', '右缘电抗器圆顶、宽圆柱局部及基座可辨，右侧出画。')],
    'E37': [('recognizable_truncated', '材质变体右缘灰色电抗器圆顶、宽圆柱局部和基座可辨，右侧截断。')],
    'E38': [('recognizable_truncated', '背景变体右缘电抗器圆柱局部、顶面和基座可辨，右侧出画。')],
    'E39': [('unknown_instance_content', '背景变体右缘相邻柜体多重叠置，窄侧面和顶面条带可见，目标实例像素边界不明确。')],
    'E40': [('unknown_instance_content', '光照变体右缘中间柜体被前柜遮挡，框含多条顶面及侧面，出画处像素归属不确定。')],
    'E41': [('recognizable_occluded', '后方电容器组宽侧背面、顶面和基座可辨，左下局部被青色前柜遮挡。')],
    'E42': [('recognizable_occluded', '后方电抗器椭圆顶及上部圆柱可见，下部被变压器遮挡；浅色端子属于前景变压器。')],
    'E43': [('recognizable_occluded', '后方电容器组宽顶面及上部侧面可辨，下部被前景柜体和变压器遮挡；端子不属于电容器。')],
    'E44': [('recognizable', '光照变体近景变压器宽主体、顶面三个端子和基座清楚，未见明显前景遮挡。')],
    'E45': [('recognizable', '柜体宽侧面、窄正面面板、顶面及基座完整可辨，无明显遮挡。')],
    'E46': [('recognizable_truncated', '近景变压器宽顶面、可见端子和宽侧面内容丰富，右侧及下部出画。')],
    'E47': [('recognizable_occluded_truncated', '左图缘变压器宽主体与顶面端子可辨，前景粗杆遮住中部，左侧出画。')],
    'E48': [('unknown_instance_content', '右缘柜体窄侧面及基座局部露出，邻柜重叠且出画，不能可靠区分目标与邻柜像素。')],
    'E49': [('recognizable', '原始条件电抗器完整圆柱、椭圆顶面及基座清楚，未见明显前景遮挡。')],
    'E50': [('unknown_instance_content', '背景变体右缘多个柜体叠置，目标窄侧面和顶面露出但实例像素边界不确定。')],
    'E51': [('unknown_instance_content', '光照变体右缘柜体窄侧面与邻柜交叠且出画，无法可靠确认目标像素分界。')],
    'E52': [('unknown_instance_content', '背景变体右缘中间柜体的顶面与窄横向侧面露出，前景柜遮住下部，框内实例归属不确定。')],
    'E53': [('recognizable', '中景柜体宽顶面、侧背面及基座完整可辨，无正面面板。')],
    'E54': [('recognizable', '入口柜体宽顶面、两侧背面和基座完整可辨，未见前景遮挡。')],
    'E55': [('recognizable_truncated', '材质变体左缘柜体宽侧面、顶面及基座可辨，左缘出画。')],
    'E56': [('recognizable_truncated', '光照变体左缘柜体宽侧面、顶面和底座可辨，左侧截断。')],
    'E57': [('recognizable_occluded', '后方变压器顶面、三个端子及上部宽主体可辨，下部被前景变压器遮挡；近端子不归给后方实例。')],
    'E58': [('unknown_instance_content', '原始条件右缘柜体与邻柜重叠，仅窄侧面和顶面条带可见，目标像素边界不明确。')],
    'E59': [('recognizable', '原始条件电容器组宽侧背面和基座清楚，表面可见斜向明暗，无明显前景遮挡。')],
    'E60': [('recognizable_occluded', '原始条件后方电抗器圆顶与上部圆柱清楚，下部被变压器遮挡；框内浅色端子属于前景。')],
    'E61': [('recognizable_occluded', '后排柜体顶面、侧面及正面面板局部可辨，左下被邻柜与前景端子遮挡。')],
    'E62': [('recognizable_truncated', '左下近景变压器宽顶面、三个端子及宽侧面可辨，左侧和下部出画。')],
    'E63': [('recognizable_occluded', '背景变体后方电容器组顶面及宽上部侧面可见，下部被柜体和变压器挡住，前景端子不归给目标。')],
    'E64': [('unknown_instance_content', '背景变体右缘柜体窄侧面、基座局部与邻柜叠置且截断，像素边界不确定。')],
    'E65': [('unknown_instance_content', '光照变体右缘柜体仅窄侧面与底座局部，邻柜重叠，不能可靠解析实例像素分界。')],
    'E66': [('recognizable_occluded', '远侧电容器组宽顶面和上部侧面可辨，下部被前景变压器及青色柜挡住；端子属于前景。')],
    'E67': [('recognizable_occluded', '背景变体远侧电容器组顶面与上部侧面可见，下部被前景多个设备遮挡。')],
    'E68': [('recognizable_truncated', '右下柜体宽顶面及侧面清楚，右侧及下部出画。')],
    'E69': [('recognizable_truncated', '背景变体近景柜体大面积顶面、上部正面及部分面板可辨，下部截断。')],
    'E70': [('recognizable_occluded', '灰色中排柜体宽顶面、侧面和低对比面板轮廓可辨，左下被邻柜挡住；不是仅基座。')],
    'E71': [('limited_occluded', '远侧电容器组窄顶面及上部横向侧面露出，下部被前景变压器遮挡，左部另受杆体遮挡，内容有限。')],
    'E72': [('unknown_instance_content', '背景变体右缘中排柜体顶面与横向窄侧面条带可见，框含前柜顶面，实例像素分界不确定。')],
    'E73': [('recognizable_occluded', '后方电容器组宽顶面、侧背面及部分基座可辨，左下被前景柜顶遮挡。')],
    'E74': [('unknown_instance_content', '极右缘极窄柜体侧面及基座片段，大片出画且邻柜重叠，无法确定充分可辨内容。')],
    'E75': [('recognizable_occluded', '后方变压器顶面三个端子与上部宽主体可辨，前景电抗器遮挡下部；圆顶不归给变压器。')],
    'E76': [('recognizable_truncated', '左缘变压器宽主体、顶面端子和基座可辨，左侧出画。')],
    'E77': [('recognizable_occluded', '灰色变压器顶面端子、宽主体和基座可辨，前景粗杆遮住主体右中部。')],
    'E78': [('unknown_instance_content', '背景变体左图缘叠置柜体仅顶面与横向侧面条带，目标截断且被近柜遮挡，实例像素归属不确定。')],
}
