"""Explicit current RGB observations; no automatic approval or label repair."""
OBS = {
 'R28': {
  0: ('limited_content','后柜面板与顶面可辨，右下被前柜遮挡。'),
  1: ('content_visible','左柜面板、宽侧面、顶面与基座完整。'),
  2: ('insufficient_content','右缘变压器仅窄侧壁、基座与地面，没有附件和完整主体。'),
  3: ('content_visible','近柜面板、顶面、侧面与基座清楚。'),
  4: ('content_visible','圆柱曲面与基座清楚，顶面视角窄。'),
 },
 'R29': {
  0: ('insufficient_content','右缘变压器框主要是地面与极少基座边缘，设备主体不可辨。'),
  1: ('content_visible','圆柱顶面、曲面与方基座完整清楚。'),
 },
 'R25': {
  0: ('limited_content','右缘变压器侧壁、窄顶面及基座可见，但无附件和完整主体，历史内容限制保留。'),
  1: ('content_visible','电抗器圆柱曲面、顶面和基座完整清楚。'),
 },
 'R26': {
  0: ('content_visible','近变压器宽主体、三附件和基座清楚。'),
  1: ('content_visible','左缘变压器宽面、部分附件及基座可辨，左侧出画。'),
  2: ('insufficient_content','后电容器只有上部窄面和顶部，框大部为前景变压器顶面与两根附件，目标内容不足。'),
 },
 'R27': {
  0: ('content_visible','右缘变压器宽侧壁、部分顶部附件和基座可辨，右侧截断。'),
  1: ('insufficient_content','左下变压器仅基座边和少量侧壁，主要为地面，目标内容不足。'),
  2: ('content_visible','电容器宽正面和基座清楚，顶部视角很窄。'),
 },
 'R22': {
  0: ('limited_content','右缘变压器仅宽侧面及基座片段，顶部附件和完整轮廓未见，不能解除历史内容限制。'),
  1: ('content_visible','圆柱顶面、曲面与基座完整清楚。'),
 },
 'R23': {
  0: ('insufficient_content','左下变压器框主要为基座斜边、地面和少许下侧壁，类别内容不足。'),
  1: ('insufficient_content','左侧变压器只见大平面片段，框混入后方蓝柜，顶部附件与完整边界未见。'),
  2: ('content_visible','电容器宽主体平面及基座可辨，顶面视角很窄。'),
 },
 'R24': {
  0: ('content_visible','近变压器宽主体、三附件及底座清楚。'),
  1: ('limited_content','左缘变压器一部分主体、一个附件与基座可见，左侧大部出画。'),
  2: ('insufficient_content','电容器框主要覆盖前景变压器顶面与侧壁，后方仅窄顶沿，没有可靠可辨主体。'),
 },
 'R19': {
  0: ('limited_content','远柜宽背面顶部可辨，右下被近柜遮住。'),
  1: ('content_visible','远柜背侧面、顶部与基座清楚。'),
  2: ('insufficient_content','后柜仅窄蓝片露在变压器和杆之间，完整单体不见。'),
  3: ('content_visible','后变压器主体、三附件及底座清楚。'),
  4: ('content_visible','中变压器宽主体和三附件可辨，下部被近电容器遮住。'),
  5: ('insufficient_content','右缘变压器标签仅极窄侧片、基座与地面，没有可辨主体。'),
  6: ('limited_content','右缘柜体部分背面、顶面与基座可见，右侧截断。'),
  7: ('insufficient_content','后柜上侧面可见但下部完全在变压器后，缺少完整内容。'),
  8: ('limited_content','近电容器顶面和两侧宽面可辨，下部出画。'),
 },
 'R20': {
  0: ('insufficient_content','近变压器只见大片顶面与一根附件，主体侧壁在画外。'),
  1: ('content_visible','远变压器宽主体、三附件与基座可辨。'),
  2: ('limited_content','后电容器顶面、左侧和基座局部可辨，右侧被变压器挡住。'),
 },
 'R21': {
  0: ('content_visible','近变压器宽主体、顶部附件与底座清楚，左部出画。'),
  1: ('content_visible','远变压器主体、三附件和基座可辨，左下前景遮挡。'),
  2: ('insufficient_content','左后变压器只露上沿及附件，框内混入近变压器顶部，主体不可分。'),
  3: ('content_visible','近柜背面、顶面与基座清楚，无面板朝相机。'),
  4: ('insufficient_content','电容器小框只见多层深色窄面，前后变压器交叠，无法可靠确认目标内容。'),
 },
 'R16': {
  0: ('content_visible','远柜背侧面、顶部、基座可辨，左下少量遮挡。'),
  1: ('insufficient_content','后排柜只露窄上侧面，框下为前景柜和变压器附件，单体不足。'),
  2: ('content_visible','远柜宽背侧面、顶部和基座可辨。'),
  3: ('limited_content','左缘远柜宽面和底座可见，但部分出画。'),
  4: ('insufficient_content','变压器框极窄，只见像素条带与地面碎片，主体不可辨。'),
  5: ('content_visible','近变压器宽主体、三附件及底座清楚，左缘截断。'),
  6: ('insufficient_content','后柜只露上侧壁和顶面，下部被变压器挡住，框混入附件。'),
  7: ('content_visible','电抗器圆柱顶面、曲面和基座完整清楚。'),
 },
 'R17': {
  0: ('limited_content','后柜面板和顶面可见，右下被前柜遮住。'),
  1: ('insufficient_content','左缘柜仅窄侧壁与基座片段，框下多为地面，完整主体不足。'),
  2: ('content_visible','右缘变压器主体、三附件、基座可辨，右侧截断。'),
  3: ('content_visible','近柜面板、顶面、右侧和基座完整清楚。'),
  4: ('content_visible','圆柱曲面、窄顶面和基座可辨。'),
 },
 'R18': {
  0: ('content_visible','变压器主体、三附件与基座清楚，右部出画。'),
  1: ('insufficient_content','下缘柜框只有蓝色顶面和地面，没有侧壁、面板或基座，不能确认为内容充分。'),
  2: ('content_visible','电抗器圆柱、椭圆顶面、方基座完整。'),
 },
 'R13': {
  0: ('content_visible','近变压器宽主体、三附件、顶面及底座清楚。'),
  1: ('limited_content','左缘变压器主体与附件可辨，左侧杆遮挡并截断。'),
  2: ('insufficient_content','后电容器仅露出顶面和窄侧壁，框内主要混入前景变压器顶面与两根附件，不能据此确认充分内容。'),
 },
 'R14': {
  0: ('content_visible','变压器宽主体、三附件及基座可辨，右侧出画。'),
  1: ('limited_content','左缘柜体只有宽侧面和基座片段，没有面板与完整轮廓。'),
  2: ('content_visible','电抗器圆柱与方基座清楚，顶面视角很窄。'),
 },
 'R15': {
  0: ('content_visible','变压器宽主体、三附件与基座可辨。'),
  1: ('limited_content','前柜顶面及正面板上部清楚，下半及左部出画。'),
  2: ('limited_content','后圆柱只露出柜顶上方一段曲面，下部与基座遮挡。'),
  3: ('insufficient_content','右缘电容器只剩极窄深色竖片与基座，框含背景地面，主体不足。'),
 },
 'R10': {
  0: ('insufficient_content','灰柜只露出前景蓝柜后的上侧平面和窄顶沿，主体下部不可见。'),
  1: ('limited_content','灰变压器宽主体与基座可见，中间粗杆遮挡；顶部附件在该角度难分。'),
  2: ('insufficient_content','后柜仅露灰色窄面，右侧混入变压器、下部混入蓝柜，完整单体无法分辨。'),
  3: ('limited_content','后圆柱右侧曲面和基座可见，左部被变压器挡住。'),
 },
 'R11': {
  0: ('insufficient_content','蓝柜上侧平面露出但下部被前景蓝柜完全遮住，不能据颜色边线批准完整内容。'),
  1: ('limited_content','蓝绿色变压器宽主体和底座可辨，粗杆遮住中段，无清楚附件细节。'),
  2: ('insufficient_content','两前景结构之间仅一小段蓝色平面，柜体整体不可分。'),
  3: ('limited_content','后方圆柱曲面与基座部分可辨，左侧前景遮挡。'),
 },
 'R12': {
  0: ('insufficient_content','背景变化后后柜仍只露上侧面与顶沿，下部被前柜挡住。'),
  1: ('limited_content','变压器主体与基座可见，中间杆遮挡，附件细节不可辨。'),
  2: ('insufficient_content','小块蓝色上侧面夹在前景之间，单体完整轮廓仍不足。'),
  3: ('limited_content','圆柱右部曲面和基座可辨，左部被前景挡住。'),
 },
 'R07': {
  0: ('insufficient_content','左缘后柜只有顶部和窄侧壁，前柜遮挡且截断，单体完整轮廓不可见。'),
  1: ('limited_content','近变压器顶面三附件与部分侧壁可辨，下部及右侧出画。'),
  2: ('limited_content','左缘近柜宽侧面、顶部与基座可见，但大部出画，无正面板。'),
  3: ('content_visible','电抗器圆柱、顶面与基座完整清楚。'),
 },
 'R08': {
  0: ('content_visible','后方变压器主体、三根附件及基座可辨。'),
  1: ('insufficient_content','右缘变压器仅窄侧壁和基座，框含大量地面，附件与主体轮廓不足。'),
  2: ('limited_content','后柜部分侧面与顶沿可见，左部被电容器挡住。'),
  3: ('content_visible','远处柜体宽侧面、顶部与基座可辨，尺度较小。'),
  4: ('content_visible','电容器宽主体、顶面及基座清楚完整。'),
 },
 'R09': {
  0: ('content_visible','远变压器主体、三附件和基座清楚。'),
  1: ('insufficient_content','近变压器主要只剩顶面与附件，主体侧壁几乎全在画外，不能把顶面当作充分完整设备监督。'),
  2: ('limited_content','后电容器宽主体、顶部与基座可见，左侧杆遮挡、右下被前景蓝块遮住。'),
 },
 'R04': {
  0: ('limited_content','后柜露出蓝色侧面与基座，右部被近处变压器遮挡，面板不可见。'),
  1: ('limited_content','后柜宽侧面及基座可见，左部被远处变压器遮挡。'),
  2: ('content_visible','变压器宽主体、基座及顶部附件可见，中间被杆遮挡。'),
  3: ('content_visible','近处变压器宽主体和基座清楚，顶部附件因视角重叠。'),
  4: ('limited_content','右缘圆柱曲面及基座可见，但顶面与右部出画，框左含近处前景。'),
  5: ('insufficient_content','左缘柜体仅露出前景后的一段窄蓝面，完整单体边界不能确认。'),
 },
 'R05': {
  0: ('limited_content','后柜仅面板局部和侧面露出，前柜明显遮挡。'),
  1: ('content_visible','中柜面板、侧面、顶部及底座可辨，左下前景局部遮挡。'),
  2: ('limited_content','左缘柜体只见侧面与底座局部，图缘截断且框含地面。'),
  3: ('insufficient_content','变压器框只覆盖单个浅色圆柱附件，未见设备主体；不能把附件当成完整设备内容。'),
  4: ('insufficient_content','后变压器仅顶部附件与窄上沿露出，下部框内为前景大变压器顶面，目标主体不可分。'),
  5: ('content_visible','正面柜体面板、顶面与基座可辨。'),
  6: ('limited_content','远处圆柱部分曲面和基座露出，下部左右被前景挡住，顶部内容不全。'),
 },
 'R06': {
  0: ('content_visible','右后柜体宽侧面、顶面和基座可辨，无面板朝相机。'),
  1: ('insufficient_content','后排柜体只见层叠窄顶面和上侧壁，无法分清完整单体。'),
  2: ('insufficient_content','前柜后方仅一段蓝面和基座，目标轮廓被前后结构混合。'),
  3: ('insufficient_content','前景后仅窄竖蓝片，主体轮廓未见。'),
  4: ('insufficient_content','左缘变压器仅侧壁与基座片段，没有顶部附件或完整主体。'),
  5: ('content_visible','中央柜体宽侧面与基座可见，顶部无面板细节。'),
  6: ('content_visible','圆柱主体与基座清楚，顶部贴边；保留顶面内容不足限制。'),
 },
 'R01': {
  0: ('content_visible','变压器宽主体、三根顶部附件和基座可辨，未见明显主体遮挡。'),
  1: ('insufficient_content','右缘电容器标签内仅窄侧壁与基座片段，并含较多地面；无法由该片段确认类别可辨内容，原风险未消失。'),
 },
 'R02': {
  0: ('content_visible','后方变压器主体、顶部三附件及底座可辨。'),
  1: ('content_visible','近处变压器宽主体、顶面三附件及基座清楚。'),
  2: ('limited_content','左缘柜体部分宽面与基座可见，但被前景粗杆遮挡并截断。'),
  3: ('limited_content','后方柜体只露侧面和顶面，左侧杆、右侧变压器混入框，归属需来源证据。'),
  4: ('insufficient_content','左缘电容器窄条框主要为地面与暗基座片段，看不到可辨识设备主体。'),
 },
 'R03': {
  0: ('limited_content','远处柜体面板和顶部可见，下部被前柜遮住。'),
  1: ('content_visible','中间柜体面板、顶部、右侧及底座可辨，左下局部前景遮挡。'),
  2: ('limited_content','左下柜体顶面与宽侧面清楚，但画缘截断且面板不见；不能用清楚顶面直接认证类别内容充分。'),
  3: ('content_visible','右缘变压器主体、三附件和基座可辨，右侧截断。'),
  4: ('content_visible','正面柜体面板、顶面和基座清楚。'),
  5: ('content_visible','圆柱、椭圆顶面和方形基座完整可辨。'),
 },
}
